Offset correction iOS
ruuvi/com.ruuvi.station.ios pull request #264
Opened 2021-05-13 09:14 UTC by mobilegurudevelopment

2021-05-14 09:22 UTC, rinat-enikeev requested changes

2021-05-14 09:22 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift
> +            }
[weak self]

2021-05-14 09:22 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift
> +            }
[weak self]

2021-05-14 09:26 UTC, rinat-enikeev commented
https://user-images.githubusercontent.com/722716/118250785-42100a00-b4c0-11eb-9554-642a9823ec4d.MP4

The most straightforward use case: 
1. calibrate temperature
2. go to Cards view
Expected: 25 (instead of 29). 
Actual: still 29

2021-05-14 09:28 UTC, rinat-enikeev commented
Additionally: Android stores data with offset in database, so it is possible to recover actual values sent by the RuuviTag while exporting. 

We would like to have the same possibility: store not just calibrated (25 instead of 30) value in DB, but received value (30) and the offset (5). And display 25, but leave possibility to export received (30) values.

2021-05-14 09:48 UTC, andreevdenis commented
In Android we store calibrated value and applied offset. In most use cases you can just display already calibrated value. If you need original value then subtract offset from calibrated value.

2021-05-14 10:19 UTC, rinat-enikeev commented
Also, please update `RealmSwift` pod in order to compile with latest Xcode (12.5)

2021-05-17 03:41 UTC, mobilegurudevelopment commented on .gitmodules
> +	url = https://github.com/mobilegurudevelopment/station.localization.git
changed to main branch

2021-05-17 03:41 UTC, mobilegurudevelopment commented on station.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
revert to original dev team

2021-05-17 03:42 UTC, mobilegurudevelopment commented on station/Classes/Model/SQLite/SensorSettingsSQLite.swift
> +        return SensorSettingsStruct(tagId: tagId, temperatureOffset: temperatureOffset, temperatureOffsetDate: temperatureOffsetDate, humidityOffset: humidityOffset, humidityOffsetDate: humidityOffse
solved

2021-05-17 03:42 UTC, mobilegurudevelopment commented on station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift
> +                sensorSettings: sensorSettings ?? SensorSettingsStruct(tagId: ruuviTag.id, temperatureOffset: nil, temperatureOffsetDate: nil, humidityOffset: nil, humidityOffsetDate: nil, pressureOf
solved

2021-05-17 03:42 UTC, mobilegurudevelopment commented on station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
> +            self.sensorSettings = SensorSettingsStruct(tagId: ruuviTag.id, temperatureOffset: nil, temperatureOffsetDate: nil, humidityOffset: nil, humidityOffsetDate: nil, pressureOffset: nil, press
solved

2021-05-17 03:43 UTC, mobilegurudevelopment commented on station/Classes/Model/Ontology/Sensor/RuuviTag/SensorSettings.swift
> +    var tagId: String { get }
changed to `ruuviTagId`

2021-05-17 03:43 UTC, mobilegurudevelopment commented on station/Classes/Model/Realm/Impl/SensorSettingsRealm.swift
> +                                            temperatureOffset: temperatureOffset.value,
solved

2021-05-17 03:43 UTC, mobilegurudevelopment commented on station/Classes/Model/Realm/Impl/SensorSettingsRealm.swift
> +        return SensorSettingsStruct(tagId: tagId!,
solved

2021-05-17 03:43 UTC, mobilegurudevelopment commented on station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift
> +            }
solved

2021-05-17 03:43 UTC, mobilegurudevelopment commented on station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift
> +            }
solved

2021-05-17 03:44 UTC, mobilegurudevelopment commented
> Also, please update `RealmSwift` pod in order to compile with latest Xcode (12.5)
solved, please run `pod install`

2021-05-17 03:45 UTC, mobilegurudevelopment commented
I've resolved all comments, please recheck.
Thank you.

2021-05-17 12:21 UTC, rinat-enikeev requested changes

2021-05-17 12:21 UTC, rinat-enikeev commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                        .sqlite.insert(db)
You've ignored my comment about storing both `raw` and `adjusted` value in the database.

2021-05-17 12:21 UTC, rinat-enikeev commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                    .sqlite.insert(db)
You've ignored requirement to store both `raw` and `adjusted` value in the database.

2021-05-17 12:21 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                    })
you are hitting db every heartbeat, my device became hot... 
any thoughts on how to optimise?

2021-05-17 12:21 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                        })
you are hitting db every broadcast. Any thought on how to optimise?

2021-05-17 12:24 UTC, rinat-enikeev commented
https://user-images.githubusercontent.com/722716/118487790-81469100-b734-11eb-92a4-a77c1044ce31.MP4

Weird behaviour, the Alert must be triggered if temperature is less than 21, the bell is blinking but no notifications. 
And on Charts view the bell is not blinking. 

Hint: check AlertService.process. Please avoid hitting DB every heartbeat.

2021-05-17 12:29 UTC, rinat-enikeev commented
What should we do with humidity calibration feature (Salt test) after this one is ready? 

![IMG_6A1E9E8A4203-1](https://user-images.githubusercontent.com/722716/118488675-67f21480-b735-11eb-924e-1575d78e61c6.jpeg)

2021-05-17 12:34 UTC, andreevdenis commented
@rinat-enikeev I removed old humidity calibration mechanism from Android version.

2021-05-17 13:43 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                        .sqlite.insert(db)
@rinat-enikeev I saw @andreevdenis comment: `In Android we store calibrated value and applied offset. In most use cases you can just display already calibrated value. If you need original value then subtract offset from calibrated value.`
I applied the same on iOS

2021-05-17 13:43 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                    .sqlite.insert(db)
@rinat-enikeev I saw @andreevdenis comment: `In Android we store calibrated value and applied offset. In most use cases you can just display already calibrated value. If you need original value then subtract offset from calibrated value.`
I applied the same on iOS

2021-05-17 13:43 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                    .sqlite.insert(db)
@rinat-enikeev I saw @andreevdenis comment: `In Android we store calibrated value and applied offset. In most use cases you can just display already calibrated value. If you need original value then subtract offset from calibrated value.`
I applied the same on iOS

2021-05-17 13:57 UTC, andreevdenis commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                        .sqlite.insert(db)
Just to make clear we have these tables in Android: 
**SensorSettings** (sensorId, humidityOffset, temperatureOffset, pressureOffset, ....) - this where we store user input from new offset correction UI

**SensorReadingsHistory** (sensorId, temperature, temperatureOffset, humidity, humidityOffset, pressure, pressureOffset,...) - to store ALL measurements from sensor (full history for the last 10 days)

**SensorLastReading** (sensorId, temperature, temperatureOffset, humidity, humidityOffset, pressure, pressureOffset,...) - one last measurement from each sensor

2021-05-17 13:59 UTC, mobilegurudevelopment commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                    })
@rinat-enikeev I'll try to store SensorSettings to local

2021-05-17 14:07 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                        .sqlite.insert(db)
@andreevdenis thank for clarification
In iOS, we have these tables:
SensorSettings (**ruuviTagId**, humidityOffset, temperatureOffset, pressureOffset, ....) - this where we store user input from new offset correction UI

RuuviTagSensorRecord (**ruuviTagId**, temperature, ~~temperatureOffset~~, humidity, humidityOffset, pressure, ~~pressureOffset~~,...) - to store ALL measurements from sensor (full history for the last 10 days)
I'll modify iOS side like Android

2021-05-18 14:20 UTC, mobilegurudevelopment commented
hi, I've updated code:
- Set 'SensorSettings' to local variable, observe to insert/update/delete from db so we can avoid hitting db each heartbeat
- I found logic of alert are represent at 2 places: CardsPresenter and AlertService, so I remove one and use logic of AlertService
- Add 3 new fields in db: temperatureOffset, humidityOffset and pressureOffset, so users can get original value by subtract with offset (like Android)

2021-05-18 14:23 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                        .sqlite.insert(db)
solved

2021-05-19 13:34 UTC, rinat-enikeev requested changes

2021-05-19 13:47 UTC, mobilegurudevelopment commented on station/Classes/Persistence/RuuviTag/Realm/RuuviTagPersistenceRealm.swift
> +                    .filter("tagId == %@", ruuviTag.luid!.value)
solved

2021-05-19 16:35 UTC, rinat-enikeev requested changes

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Model/Realm/Impl/SensorSettingsRealm.swift
> +    @objc dynamic var tagId: String?
let's make it non optional 
`@objc dynamic var tagId: String == ""`

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Model/Realm/Impl/SensorSettingsRealm.swift
> +        tagId = ruuviTag.luid?.value
let's prepare for `network` sensors 

`tagId = ruuviTag.luid?.value ?? ruuviTag.macId?.value ?? ""`

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Model/Realm/Impl/SensorSettingsRealm.swift
> +        return SensorSettingsStruct(ruuviTagId: tagId!,
and avoid force unwrap that will crash for network sensor (it doesn't have local id)

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +            if sqliteSensorSettings != nil {
`if let sqliteSensorSettings = sqliteSensorSettings`

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                sqliteSensorSettings = Settings(ruuviTagId: ruuviTag.id,
`let sqliteSensorSettings = ` in order to avoid force unwrap

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift
> +                    try sqliteSensorSettings!.insert(db)
check previous comment - force unwrap should be avoided

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                            guard let `self` = self else { return }
why not follow this project code style with `sSelf`?

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                    // self?.updateAlertState(for: viewModel)
why not removed?

2021-05-19 16:35 UTC, rinat-enikeev commented on station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
> +                        // self?.updateAlertState(for: viewModel)
why not removed?

2021-05-19 16:37 UTC, rinat-enikeev commented
My vision for the next steps is: 

1. respect the latest comments
2. merge to `dev`
3. merge `dev` to `network`
4. remove legacy `humidity calibration` feature
5. ensure `network` tags respect `offset calibration`
6. release for alpha test

2021-05-20 10:59 UTC, rinat-enikeev approved these changes

2021-05-20 11:45 UTC, merged