DFU Firmware Update
ruuvi/com.ruuvi.station.ios pull request #397
Opened 2021-06-07 06:06 UTC by mobilegurudevelopment

2021-06-07 07:59 UTC, rinat-enikeev requested changes

2021-06-07 07:59 UTC, rinat-enikeev commented on station.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = sg.megapixel.test;
this should not go into main repo

2021-06-07 09:03 UTC, rinat-enikeev commented
![IMG_52AC70162DB3-1](https://user-images.githubusercontent.com/722716/120989473-07d11a00-c799-11eb-92e3-47fb13a7f3df.jpeg)

Missing localisation for "Open document picker"

2021-06-07 09:03 UTC, rinat-enikeev commented
![IMG_393D8B1B364F-1](https://user-images.githubusercontent.com/722716/120989631-2f27e700-c799-11eb-98a6-fe6c91e9b284.jpeg)
missing i18n for buttons

2021-06-07 09:06 UTC, rinat-enikeev commented
![IMG_4DA1BE75DA43-1](https://user-images.githubusercontent.com/722716/120989986-8af27000-c799-11eb-9f4c-2dec8c285feb.jpeg)
missing i18n for "Finish"

2021-06-07 09:10 UTC, rinat-enikeev commented
User should not be able to swipe down the view controller during the DFU process. 

Please check how it is done for Discover module here: 
https://github.com/ruuvi/com.ruuvi.station.ios/blob/8d48c588656065aed818bf92a3a527b39eacc7c9/station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift#L41-L41

https://github.com/ruuvi/com.ruuvi.station.ios/blob/8d48c588656065aed818bf92a3a527b39eacc7c9/station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift#L110

2021-06-08 00:12 UTC, mobilegurudevelopment commented
> User should not be able to swipe down the view controller during the DFU process.
> 
> Please check how it is done for Discover module here:
> https://github.com/ruuvi/com.ruuvi.station.ios/blob/8d48c588656065aed818bf92a3a527b39eacc7c9/station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift#L41-L41
> 
> https://github.com/ruuvi/com.ruuvi.station.ios/blob/8d48c588656065aed818bf92a3a527b39eacc7c9/station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift#L110

Updated

2021-06-08 00:12 UTC, mobilegurudevelopment commented on station.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = sg.megapixel.test;
solved

2021-06-08 00:13 UTC, mobilegurudevelopment commented
@rinat-enikeev I solved your mentioned issues, please help to recheck. Thanks

2021-06-08 07:10 UTC, rinat-enikeev commented
`Next` button on First screen is not translated, `Progress` text on Flash screen is not translated.

2021-06-08 10:22 UTC, mobilegurudevelopment commented
> `Next` button on First screen is not translated, `Progress` text on Flash screen is not translated.

updated

2021-06-09 13:10 UTC, merged